services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
  # backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - postgres
  #     - redis
  #   command: yarn start:prod

volumes:
  redis_data:
